# Define the namespace where Superset will be installed
namespace: superset

# Database configuration
postgresql:
  postgresqlUsername: supersetpostgres
  postgresqlPassword: SuperPGadmin@2024
  postgresqlDatabase: superset

configOverrides:
  secret: |
    SECRET_KEY = '1sabLCfgIJhMl4q9JneURDWw2g/HlCwxY72h84n5LiKRK58p+6HpjamD'


bootstrapScript: |
  #!/bin/bash
  pip install psycopg2-binary pyhive trino
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
