apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: spark-apps
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: aGl2ZQ==         # Base64 encoded value of 'hive'
  POSTGRES_PASSWORD: R1VZZ3Nqc2pAMTIz  # Base64 encoded value of 'GUYgsjsj@123'