apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: osds-cluster
spec:
  kafka:
    version: 3.7.0
    replicas: 1  # You can scale this depending on your needs
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          class: standard  # GCP Persistent Disk Storage Class, you can also use `ssd` for faster disk
          deleteClaim: false
  zookeeper:
    replicas: 1  # You can scale this depending on your needs (for HA, you should have at least 3 replicas)
    storage:
      type: persistent-claim
      size: 2Gi
      class: standard  # GCP Persistent Disk Storage Class
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
